repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: uv-lock
        name: uv lock
        entry: uv lock
        pass_filenames: false
        files: ^(uv\.lock|pyproject\.toml)$
        language: system
      - id: uv-export
        name: uv export
        entry: uv export
        args: ["--frozen", "--output-file=requirements.txt"]
        pass_filenames: false
        files: ^uv\.lock$
        language: system
